language: cpp

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sh setup-travis.sh; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sh setup-travis.sh; fi

script: travis_wait sh getdeps.sh && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && ./tests/CryptoEngineTest && make install

branches:
  only:
    - master

notifications:
  email: true

addons:
  hosts:
    - travis.dev

os:
  - linux
  - osx